name: GitHub Actions CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: node:14.19.3
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Run tests
        run: |
          CI=true yarn test
